"""V3.5 source identity, timeline, and exact-mapping contracts."""

from shiliu.evidence.contracts import (
    CHUNK_MAPPING_VERSION,
    REPLAY_IMPLEMENTATION_VERSION,
    SEARCH_CANDIDATE_CONTRACT_VERSION,
    SOURCE_CHUNK_POLICY_VERSION,
    SOURCE_IDENTITY_VERSION,
    SOURCE_IDENTITY_V1_VERSION,
    SOURCE_VERSION_AUTHORITY_VERSION,
    STAGE1_ERROR_CODES,
    TIMELINE_POLICY_VERSION,
    ChunkSegmentMapping,
    EvidenceContractError,
    ParsedSourceArtifact,
    RawEvidenceSegment,
    RetrievalChunkReference,
    SearchRawUnitCandidate,
    SearchCandidateSet,
    SearchCandidateVideo,
    SourceArtifactReference,
    SourceVersionBinding,
    TRACE_POLICY_VERSION,
    TimelineRun,
)
from shiliu.evidence.mapping import map_chunk_in_artifact, map_retrieval_chunk, replay_source_chunks
from shiliu.evidence.authority import (
    bind_live_current_version,
    bind_pinned_version,
    bind_snapshot_manifest_version,
)
from shiliu.evidence.audit import MappingAuditSummary, audit_snapshot_chunk_mappings
from shiliu.evidence.search import EvidenceSearchService
from shiliu.evidence.source import (
    authoritative_raw_json_path,
    load_source_artifact,
    make_segment_digest,
    make_segment_id,
    make_source_artifact_id,
    make_source_artifact_id_v1,
    require_same_timeline_run,
    source_version_for_bytes,
)

__all__ = [
    "CHUNK_MAPPING_VERSION",
    "REPLAY_IMPLEMENTATION_VERSION",
    "SEARCH_CANDIDATE_CONTRACT_VERSION",
    "SOURCE_CHUNK_POLICY_VERSION",
    "SOURCE_IDENTITY_VERSION",
    "SOURCE_IDENTITY_V1_VERSION",
    "SOURCE_VERSION_AUTHORITY_VERSION",
    "STAGE1_ERROR_CODES",
    "TIMELINE_POLICY_VERSION",
    "ChunkSegmentMapping",
    "EvidenceContractError",
    "EvidenceSearchService",
    "MappingAuditSummary",
    "ParsedSourceArtifact",
    "RawEvidenceSegment",
    "RetrievalChunkReference",
    "SearchRawUnitCandidate",
    "SearchCandidateSet",
    "SearchCandidateVideo",
    "SourceArtifactReference",
    "SourceVersionBinding",
    "TRACE_POLICY_VERSION",
    "TimelineRun",
    "authoritative_raw_json_path",
    "audit_snapshot_chunk_mappings",
    "bind_live_current_version",
    "bind_pinned_version",
    "bind_snapshot_manifest_version",
    "load_source_artifact",
    "make_segment_digest",
    "make_segment_id",
    "make_source_artifact_id",
    "make_source_artifact_id_v1",
    "map_chunk_in_artifact",
    "map_retrieval_chunk",
    "replay_source_chunks",
    "require_same_timeline_run",
    "source_version_for_bytes",
]
